### PR TITLE
fix: improve error messages for better developer feedback

### LINKED ISSUE #92: Improve error messages with suggestions and context
Our error messages are functional but not very helpful. Compare:

```
Before: "missing field: email"
After:  "Missing required field 'email' in JSON body"

Before: "invalid path param"
After:  "Path parameter 'id' must be a valid integer, got 'abc'"
```

Audit `rapina/src/error.rs`, `rapina/src/extract.rs`, and `rapina/src/config.rs`. Make every message tell you what went wrong and what was expected.

### PR DESCRIPTION
**Pull request by uemuradevexe**
Fixes #92

Improves error messages to clearly describe what went wrong
and what was expected, replacing generic errors with
actionable feedback

### CODE REVIEW

File: rapina/src/extract.rs [hunk 1]
```diff
@@ -462,14 +471,19 @@ where
...
     ) -> Result<Self, Error> {
-        let value = params
-            .values()
-            .next()
-            .ok_or_else(|| Error::bad_request("missing path param"))?;
-
-        let parsed = value
-            .parse::<T>()
-            .map_err(|e| Error::bad_request(format!("invalid path param: {}", e)))?;
+        let (param_name, value) = params.iter().next().ok_or_else(|| {
```
Comment (arferreira) [inline rapina/src/extract.rs:475]: this might not be a framework bug lol
could be user error if they user for example a Path<T> on a route without path params
consider something like: Missing path parameter. Ensure your route pattern includes a parameter like /:id
