### PR TITLE
Fix build of rapina new command

### LINKED ISSUE #108: [Bug]: Build fails after "rapina new"
### Description

Hi,

I tried to execute `rapina new` and follow-up with a `cd` and `rapina dev` as outlined by the CLI.
There is a build error happening; I have not touched any of the files created by rapina. It was a fresh folder created by Rapina, no previous Rust content was present.

### Steps to Reproduce

Execute:  
1. `rapina new rapina-test`
2. `cd .\rapina-test\`
3. `rapina dev`

### Expected Behavior

Build is successful for a new Rapina project

### Code Example

```rust

```

### Environment

- Rapina version: main (at https://github.com/arferreira/rapina/commit/aed44f2d95e4bbba68b80b071922c580a84ccfad)
- Rust version: `rustc 1.89.0 (29483883e 2025-08-04)`
- OS: Windows 10

### Error Output / Logs

```shell
PS C:\Development\rust> rapina new rapina-test

  Creating new Rapina project: rapina-test

  ✓ Created Cargo.toml
  ✓ Created src/main.rs
  ✓ Created .gitignore

  🎉 Project created successfully!

  Next steps:
    cd rapina-test
    rapina dev

PS C:\Development\rust> cd .\rapina-test\
PS C:\Development\rust\rapina-test> rapina dev

 ╭───────────────────────────────────────────────────────────╮
 │               Rapina CLI - Development Mode               │
 ├───────────────────────────────────────────────────────────┤
 │                                                           │
 │ Serving at: http://127.0.0.1:3000                         │
 │ Routes:     http://127.0.0.1:3000/.__rapina/routes        │
 │                                                           │
 │ For production: cargo build --release                     │
 │                                                           │
 ╰───────────────────────────────────────────────────────────╯

INFO Building project...
    Updating crates.io index
     Locking 208 packages to latest Rust 1.89.0 compatible versions
      Adding crypto-common v0.1.6 (available: v0.1.7)
 Downloading crates ...
  Downloaded rapina-macros v0.2.0
  Downloaded jsonwebtoken v10.3.0
  Downloaded zmij v1.0.17
  Downloaded rapina v0.2.0
  Downloaded proc-macro2 v1.0.106
  Downloaded uuid v1.20.0
  Downloaded socket2 v0.6.2
  Downloaded quote v1.0.44
  Downloaded libm v0.2.16
  Downloaded zerocopy v0.8.34
   Compiling proc-macro2 v1.0.106
   Compiling quote v1.0.44
   Compiling unicode-ident v1.0.22
   Compiling cfg-if v1.0.4
   Compiling zeroize v1.8.2
   Compiling typenum v1.19.0
   Compiling version_check v0.9.5
   Compiling const-oid v0.9.6
   Compiling subtle v2.6.1
   Compiling smallvec v1.15.1
   Compiling base64ct v1.8.3
   Compiling itoa v1.0.17
   Compiling stable_deref_trait v1.2.1
   Compiling windows-link v0.2.1
   Compiling libm v0.2.16
   Compiling autocfg v1.5.0
   Compiling getrandom v0.2.17
   Compiling windows_x86_64_msvc v0.53.1
   Compiling serde_core v1.0.228
   Compiling pem-rfc7468 v0.7.0
   Compiling once_cell v1.21.3
   Compiling pin-project-lite v0.2.16
   Compiling rand_core v0.6.4
   Compiling windows-sys v0.61.2
   Compiling fnv v1.0.7
   Compiling bytes v1.11.0
   Compiling serde v1.0.228
   Compiling litemap v0.8.1
   Compiling writeable v0.6.2
   Compiling der v0.7.10
   Compiling parking_lot_core v0.9.12
   Compiling generic-array v0.14.9
   Compiling zerocopy v0.8.34
   Compiling ff v0.13.1
   Compiling tracing-core v0.1.36
   Compiling futures-core v0.3.31
   Compiling zmij v1.0.17
   Compiling num-traits v0.2.19
   Compiling icu_properties_data v2.1.2
   Compiling scopeguard v1.2.0
   Compiling windows-targets v0.53.5
   Compiling icu_normalizer_data v2.1.1
   Compiling base16ct v0.2.0
   Compiling windows-sys v0.60.2
   Compiling lock_api v0.4.14
   Compiling group v0.13.0
   Compiling spki v0.7.3
   Compiling serde_json v1.0.149
   Compiling spin v0.9.8
   Compiling semver v1.0.27
   Compiling pkcs8 v0.10.2
   Compiling cpufeatures v0.2.17
   Compiling lazy_static v1.5.0
   Compiling parking_lot v0.12.5
   Compiling syn v2.0.114
   Compiling rustc_version v0.4.1
   Compiling http v1.4.0
   Compiling memchr v2.7.6
   Compiling regex-syntax v0.8.8
   Compiling ident_case v1.0.1
   Compiling strsim v0.11.1
   Compiling equivalent v1.0.2
   Compiling hashbrown v0.16.1
   Compiling curve25519-dalek v4.1.3
   Compiling futures-sink v0.3.31
   Compiling time-core v0.1.8
   Compiling httparse v1.10.1
   Compiling num-conv v0.2.0
   Compiling crypto-common v0.1.6
   Compiling block-buffer v0.10.4
   Compiling crypto-bigint v0.5.5
   Compiling digest v0.10.7
   Compiling sec1 v0.7.3
   Compiling thiserror v2.0.18
   Compiling powerfmt v0.2.0
   Compiling hmac v0.12.1
   Compiling signature v2.2.0
   Compiling sha2 v0.10.9
   Compiling percent-encoding v2.3.2
   Compiling num-integer v0.1.46
   Compiling hkdf v0.12.4
   Compiling socket2 v0.6.2
   Compiling rfc6979 v0.4.0
   Compiling num-bigint-dig v0.8.6
   Compiling mio v1.1.1
   Compiling regex-automata v0.4.13
   Compiling num-iter v0.1.45
   Compiling form_urlencoded v1.2.2
   Compiling deranged v0.5.5
   Compiling indexmap v2.13.0
   Compiling http-body v1.0.1
   Compiling time-macros v0.2.26
   Compiling proc-macro-error-attr2 v2.0.0
   Compiling pin-utils v0.1.0
   Compiling getrandom v0.3.4
   Compiling libc v0.2.180
   Compiling try-lock v0.2.5
   Compiling slab v0.4.11
   Compiling atomic-waker v1.1.2
   Compiling utf8_iter v1.0.4
   Compiling ref-cast v1.0.25
   Compiling want v0.3.1
   Compiling ppv-lite86 v0.2.21
   Compiling elliptic-curve v0.13.8
   Compiling num-bigint v0.4.6
   Compiling ed25519 v2.2.3
   Compiling pkcs1 v0.7.5
   Compiling futures-channel v0.3.31
   Compiling futures-task v0.3.31
   Compiling rand_chacha v0.3.1
   Compiling ecdsa v0.16.9
   Compiling primeorder v0.13.6
   Compiling base64 v0.22.1
   Compiling httpdate v1.0.3
   Compiling log v0.4.29
   Compiling futures-util v0.3.31
   Compiling rand v0.8.5
   Compiling pem v3.0.6
   Compiling tracing-log v0.2.0
   Compiling time v0.3.46
   Compiling p384 v0.13.1
   Compiling p256 v0.13.2
   Compiling nu-ansi-term v0.50.3
   Compiling sharded-slab v0.1.7
   Compiling thread_local v1.1.9
   Compiling dyn-clone v1.0.20
   Compiling tower-service v0.3.3
   Compiling ryu v1.0.22
   Compiling uuid v1.20.0
   Compiling http-body-util v0.1.3
   Compiling dotenvy v0.15.7
   Compiling regex v1.12.2
   Compiling matchers v0.2.0
   Compiling synstructure v0.13.2
   Compiling darling_core v0.20.11
   Compiling serde_derive_internals v0.29.1
   Compiling proc-macro-error2 v2.0.1
   Compiling zerofrom-derive v0.1.6
   Compiling yoke-derive v0.8.1
   Compiling zerovec-derive v0.11.2
   Compiling displaydoc v0.2.5
   Compiling serde_derive v1.0.228
   Compiling tokio-macros v2.6.0
   Compiling tracing-attributes v0.1.31
   Compiling thiserror-impl v2.0.18
   Compiling curve25519-dalek-derive v0.1.1
   Compiling ref-cast-impl v1.0.25
   Compiling rsa v0.9.10
   Compiling schemars_derive v1.2.0
   Compiling rapina-macros v0.2.0
   Compiling tokio v1.49.0
   Compiling zerofrom v0.1.6
   Compiling yoke v0.8.1
   Compiling tracing v0.1.44
   Compiling simple_asn1 v0.6.3
   Compiling darling_macro v0.20.11
   Compiling zerovec v0.11.5
   Compiling zerotrie v0.2.3
   Compiling darling v0.20.11
   Compiling ed25519-dalek v2.2.0
   Compiling validator_derive v0.20.0
   Compiling tinystr v0.8.2
   Compiling potential_utf v0.1.4
   Compiling icu_collections v2.1.1
   Compiling icu_locale_core v2.1.1
   Compiling icu_provider v2.1.1
   Compiling tracing-serde v0.2.0
   Compiling jsonwebtoken v10.3.0
   Compiling serde_urlencoded v0.7.1
   Compiling schemars v1.2.0
   Compiling icu_normalizer v2.1.1
   Compiling icu_properties v2.1.2
   Compiling tracing-subscriber v0.3.22
   Compiling idna_adapter v1.2.1
   Compiling idna v1.1.0
   Compiling url v2.5.8
   Compiling tokio-util v0.7.18
   Compiling validator v0.20.0
   Compiling h2 v0.4.13
   Compiling hyper v1.8.1
   Compiling hyper-util v0.1.19
   Compiling rapina v0.2.0
   Compiling rapina-test v0.1.0 (C:\Development\rust\rapina-test)
error[E0277]: the trait bound `MessageResponse: JsonSchema` is not satisfied
   --> src\main.rs:16:26
    |
15  | #[get("/")]
    | ----------- required by a bound introduced by this call
16  | async fn hello() -> Json<MessageResponse> {
    |                          ^^^^^^^^^^^^^^^ the trait `JsonSchema` is not implemented for `MessageResponse`
    |
    = help: the following other types implement trait `JsonSchema`:
              &'a T
              &'a mut T
              ()
              (T0, T1)
              (T0, T1, T2)
              (T0, T1, T2, T3)
              (T0, T1, T2, T3, T4)
              (T0, T1, T2, T3, T4, T5)
            and 132 others
note: required by a bound in `SchemaGenerator::into_root_schema_for`
   --> C:\Users\juv\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\schemars-1.2.0\src\generate.rs:480:45
    |
480 |     pub fn into_root_schema_for<T: ?Sized + JsonSchema>(mut self) -> Schema {
    |                                             ^^^^^^^^^^ required by this bound in `SchemaGenerator::into_root_schema_for`

error[E0277]: the trait bound `HealthResponse: JsonSchema` is not satisfied
   --> src\main.rs:23:27
    |
22  | #[get("/health")]
    | ----------------- required by a bound introduced by this call
23  | async fn health() -> Json<HealthResponse> {
    |                           ^^^^^^^^^^^^^^ the trait `JsonSchema` is not implemented for `HealthResponse`
    |
    = help: the following other types implement trait `JsonSchema`:
              &'a T
              &'a mut T
              ()
              (T0, T1)
              (T0, T1, T2)
              (T0, T1, T2, T3)
              (T0, T1, T2, T3, T4)
              (T0, T1, T2, T3, T4, T5)
            and 132 others
note: required by a bound in `SchemaGenerator::into_root_schema_for`
   --> C:\Users\juv\.cargo\registry\src\index.crates.io-1949cf8c6b5b557f\schemars-1.2.0\src\generate.rs:480:45
    |
480 |     pub fn into_root_schema_for<T: ?Sized + JsonSchema>(mut self) -> Schema {
    |                                             ^^^^^^^^^^ required by this bound in `SchemaGenerator::into_root_schema_for`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `rapina-test` (bin "rapina-test") due to 2 previous errors

Error: Build failed
```

### PR DESCRIPTION
**Pull request by juv**
Fixes #108

### CODE REVIEW

File: rapina-cli/src/commands/new.rs [hunk 1]
```diff
@@ -177,6 +178,7 @@ mod tests {
     #[test]
     fn test_validate_project_name_invalid() {
         assert!(validate_project_name("").is_err());
+        assert!(validate_project_name(".").is_err());
```
Comment (arferreira) [inline rapina-cli/src/commands/new.rs:181]: Good catch!

**Review by arferreira — APPROVED** [review]
Looks good to me!
